const express = require('express')
const router = express.Router()
const me = require('..//app/controller/MeController')
const account = require('..//app/controller/LoginController')
const softMiddlerwarse = require('..//app/middlewarses/SoftMiddlewarse')
router.get('/me/getNotification', me.getNotification)
router.get('/account/search', account.searchUser)
router.get('/me/getrooms', me.getRooms)
router.get('/me/getmessages/:userID', softMiddlerwarse, me.getMessages)
module.exports = router